name: launching website
on:
  push:

jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: check the actions
        uses: actions/checkout@v4

      - name: Docker login
        run: |
           echo "${{secrets.DOCKER_PASSWORD}} " |\
           docker login -u "sruthidoc07" --password-stdin

      - name: Docker build
        run: |
           docker build -t sruthidoc07/websi:v1 .

      - name: Docker push
        run: |
           docker push sruthidoc07/websi:v1

      - name: deploy to ec2
        uses: appleboy/ssh-action@v1

        with:
          host: ${{secrets.EC2_HOST }}
          username: ${{secrets.EC2_USER }}
          key: ${{secrets.EC2_SSHKEY }}

          script: |
            docker pull sruthidoc07/websi:v1
            docker stop  websi || true
            docker rm websi || true
            docker run -d --name websi -p 80:80 sruthidoc07/websi:v1

